version: "3.9"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app/front-end
      - /app/front-end/node_modules
    stdin_open: true
    tty: true
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
